import React, { useState, useEffect } from 'react';
import Masonry from 'react-masonry-css';
import axios from 'axios';
import { Search, Loader2 } from 'lucide-react';
import ImageCard from '../components/ImageCard';

const Home = () => {
  const [posts, setPosts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [debouncedSearch, setDebouncedSearch] = useState('');

  // Debounce search
  useEffect(() => {
    const handler = setTimeout(() => {
      setDebouncedSearch(search);
    }, 500);
    return () => clearTimeout(handler);
  }, [search]);

  useEffect(() => {
    const fetchPosts = async () => {
      setLoading(true);
      try {
        const { data } = await axios.get(`/posts?search=${debouncedSearch}`);
        setPosts(data);
      } catch (error) {
        console.error('Error fetching posts', error);
      } finally {
        setLoading(false);
      }
    };
    fetchPosts();
  }, [debouncedSearch]);

  const breakpointColumnsObj = {
    default: 4,
    1100: 3,
    700: 2,
    500: 1
  };

  return (
    <div className="py-8">
      {/* Hero Section */}
      <div className="text-center max-w-3xl mx-auto mb-16 relative">
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-full h-48 bg-primary/20 blur-[100px] rounded-full pointer-events-none"></div>
        <h1 className="text-5xl md:text-6xl font-extrabold mb-6 tracking-tight relative">
          Community <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary to-secondary">Showcase</span>
        </h1>
        <p className="text-gray-400 text-lg mb-10 relative">
          Browse through a gallery of stunning images generated by our community using state-of-the-art AI models.
        </p>

        {/* Search Bar */}
        <div className="relative max-w-xl mx-auto group z-10">
          <div className="absolute inset-0 bg-gradient-to-r from-primary/30 to-secondary/30 rounded-2xl blur-xl group-hover:blur-2xl transition-all opacity-50"></div>
          <div className="relative flex items-center bg-surface border border-white/10 rounded-2xl overflow-hidden focus-within:border-primary/50 transition-colors">
            <Search className="w-6 h-6 text-gray-500 ml-4 shrink-0" />
            <input
              type="text"
              placeholder="Search prompts or styles..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full bg-transparent text-white px-4 py-4 focus:outline-none placeholder-gray-500"
            />
          </div>
        </div>
      </div>

      {/* Grid */}
      {loading ? (
        <div className="flex justify-center items-center py-20">
          <Loader2 className="w-10 h-10 text-primary animate-spin" />
        </div>
      ) : posts.length > 0 ? (
        <Masonry
          breakpointCols={breakpointColumnsObj}
          className="masonry-grid"
          columnClassName="masonry-grid_column"
        >
          {posts.map((post) => (
            <ImageCard key={post._id} {...post} />
          ))}
        </Masonry>
      ) : (
        <div className="text-center py-20 text-gray-500">
          <p className="text-xl">No images found for your search.</p>
          <button 
            onClick={() => setSearch('')}
            className="text-primary hover:underline mt-2"
          >
            Clear Search
          </button>
        </div>
      )}
    </div>
  );
};

export default Home;
